# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0003_auto_20170219_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='text_comment',
        ),
    ]
