# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0004_auto_20170224_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
