# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0005_remove_comments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(default='no author', max_length=200),
        ),
    ]
